create table customer
(
    id          integer generated by default as identity,
    customer_id varchar(255),
    dob         date,
    firstname   varchar(255),
    gender      integer,
    lastname    varchar(255),
    primary key (id)
);
create table customer_order
(
    id          integer generated by default as identity,
    order_id    varchar(255),
    total       numeric,
    customer_id integer,
    status      integer,
    datetime    timestamp with time zone,
    updated    timestamp with time zone,
    primary key (id)
);
create table order_line
(
    id         integer generated by default as identity,
    order_id   integer,
    quantity   integer,
    product_id varchar(255),
    name       varchar(255),
    price      numeric,
    category   integer,
    primary key (id)
);
ALTER TABLE order_line
    ADD FOREIGN KEY (order_id)
        REFERENCES customer_order (id);
ALTER TABLE customer_order
    ADD FOREIGN KEY (customer_id)
        REFERENCES customer (id);